### PR TITLE
Opt Out API DELETE Endpoint

### PR DESCRIPTION
**Pull request by g1039**

### CODE REVIEW

**Comment by g1039** [comment]
@hodgestar Ready for review

**Comment by g1039** [comment]
@hodgestar Ready for review

**Comment by hodgestar** [comment]
@TrevorOctober You need to push your develop branch to GitHub before I can review.

**Comment by hodgestar** [comment]
@TrevorOctober Not sure why this was closed?

**Comment by g1039** [comment]
@hodgestar I received an error on Travis "Build #81 has errored". What did I do wrong?

**Comment by hodgestar** [comment]
@TrevorOctober You deleted the branch, so Travis can no longer find it to do builds with. You can read the errors by clicking on the red cross next to the commit or going to the Travis build history at https://travis-ci.org/praekelt/go-optouts-api/builds.

**Comment by g1039** [comment]
@hodgestar Travis is happy now :-)

**Pull request closed without merging**
